---
- name: Install required packages for Docker
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: yes

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker package
  become: yes
  apt:
    name: docker-ce
    update_cache: yes

- name: Install pip3 package
  become: yes
  apt:
    name: python3-pip

# Need as we use the docker_xxx Ansible modules
- name: Install Docker Module for Python
  become: yes
  pip:
    name: docker

- name: Configure Docker rotation logs for containers
  become: yes
  template:
    src: docker-container
    dest: /etc/logrotate.d/docker-container
