---
- name: Create api-xxx service
  become: yes
  template:
    src: api.service.j2
    dest: "/etc/systemd/system/{{ api_container_name }}-{{ current_env }}.service"
  notify: restart api-xxx service

- name: Start and enable api-xxx service
  become: yes
  systemd:
    name: "{{ api_container_name }}-{{ current_env }}"
    state: started
    enabled: yes
