version: '3'
services:
  db:
    image: timescale/timescaledb-postgis:1.7.4-pg11 
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=monitorfishdb
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
  
volumes:
  db-data:
    driver: local