---
- hosts: api
  tasks:
    - name: Login to Github Docker registry
      import_tasks: docker_registry_login.yml

    - name: Start API container
      become: yes
      docker_container:
        image: "{{ docker_registry_url }}/{{ docker_image_path }}:{{ docker_image_tag }}"
        name: "{{ api_container_name }}-{{ current_env }}"
        state: started
        restart: yes
        ports:
          - "{{ api_container_port }}:8880"
        env:
          CURRENT_ENV: "{{ current_env }}"

          # DB
          ENV_DB_URL: "jdbc://{{ vault_db_user }}:{{ vault_db_password }}@localhost:5432/{{ db_name }}"

    - name: Add api-xxx service (systemd)
      include_role:
        name: api_service

    - name: Upgrade app image when a new one is found in the docker registry
      include_role:
        name: upgrade_app_image
      tags: [never, auto_upgrade]

    - name: Remove all non used Docker images (= not linked with a container)
      become: yes
      docker_prune:
        images: yes
        images_filters:
          dangling: false
