---
- name: Copy upgrade app image task
  become: yes
  template:
    src: upgrade_app_image.j2
    dest: "/usr/bin/upgrade_app_image.sh"

- name: Run upgrade app long running task
  become: true
  shell: /usr/bin/upgrade_app_image.sh
  async: 31104000               # 60*60*24*30*12 = 12 month
  poll: 0
